baseURL: http://operators.network/
languageCode: en-gb
title: Operators Network
theme: hugo-fresh
copyright: Operators Network (c) {{ YEAR }}
#googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  
  # Used as meta data; describe your site to make Google Bots happy
  description: "Operators Network -- The angel syndicate for CTO operators"
  
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/operatorsnetwork-logo-RVB.svg
    link: /

  font: 
    name: "NowAltMedium"
    sizes: [400,600]

  favicon: "/favicon/"
  
  hero:
    # Main hero title
    title: Operators Network
    # Hero subtitle (optional)
    subtitle: The Angel Syndicate for CTO Operators
    herotext: The CTO Operators.Network is a syndicate of operational CTO angel investors. <br /><br /> Companies receiving investment from the network will have access to support and guidance from experienced CTOs with a large amount of combined experience.
    # Button text
#    buttontext: Download Intro Deck
    # Where the main hero button links to
#    buttonlink: "/operators-network-introduction.pdf"
    # Hero image (from static/images/___)
    image: illustrations/operators-network-headline.svg

  navbar:
    - title: Download Intro Deck
      url: "/operators-network-introduction.pdf"

    # Footer logos (from static/images/logos/clients/___.svg)

## Use these for when we decide to publicise our investments
#    clientlogos:
#    - systek
#    - tribe
#    - kromo
#    - infinite
#    - gutwork
 
#  footer:
    # Logo (from /images/logos/___)
#    logo: operatorsnetwork-logo-RVB.svg
