baseURL = 'http://operators.network'
title = 'Operators Network'
languageCode = 'en-gb'


# --sample config below this line--

paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Operators Network"
description = "The Angel Syndicate for CTO Operators"
keywords = [ "Investors", "Portfolio", "Angel", "Syndicate", "VC" ]
# author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = true
#ShowReadingTime = true
#ShowShareButtons = true
#ShowPostNavLinks = true
#ShowBreadCrumbs = true
#ShowCodeCopyButtons = false
#disableSpecial1stPost = false
#disableScrollToTop = false
#comments = false
#hidemeta = false
#hideSummary = false
#showtoc = false
#tocopen = false

  [params.assets]
#  favicon = "<link / abs url>"
#  favicon16x16 = "<link / abs url>"
#  favicon32x32 = "<link / abs url>"
#  apple_touch_icon = "<link / abs url>"
#  safari_pinned_tab = "<link / abs url>"

  [params.label]
#  text = "Home"
#  icon = "/apple-touch-icon.png"
#  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Operators Network"
  subtitle = "The Angel Syndicate for CTO Operators"
  imageUrl = "static/operatorsnetwork-logo-mono-RVB_02.png"
#  imageWidth = 120
#  imageHeight = 120
  imageTitle = "Operators Network"

#    [[params.profileMode.buttons]]
#    name = "Posts"
#    url = "posts"

#    [[params.profileMode.buttons]]
#    name = "Tags"
#    url = "tags"

  [params.homeInfoParams]
  Title = "Operators Network"
  Content = "The Angel Syndicate for CTO Operators"
	
#  [[params.socialIcons]]
#  name = "twitter"
#  url = "https://twitter.com/"

#  [[params.socialIcons]]
#  name = "stackoverflow"
#  url = "https://stackoverflow.com"

#  [[params.socialIcons]]
#  name = "github"
#  url = "https://github.com/"

#[params.analytics.google]
#SiteVerificationTag = "XYZabc"

#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

#[params.analytics.yandex]
#SiteVerificationTag = "XYZabc"

#  [params.cover]
#  hidden = true
#  hiddenInList = true
#  hiddenInSingle = true

# [params.editPost]
#  URL = "https://github.com/robelkin/operators.network/content"
#  Text = "Suggest Changes"
#  appendFilePath = true

#  [params.fuseOpts]
#  isCaseSensitive = false
#  shouldSort = true
#  location = 0
#  distance = 1_000
#  threshold = 0.4
#  minMatchCharLength = 0
#  keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "blog"
#name = "blog"
#url = "/blog/"
#weight = 20
